### ISSUE TITLE
如何与特定人建立共享文件夹？

### ISSUE THREAD

**Issue by JustLuoxi** [hpc-admin-sist/DockerMonitorG#1]
**问题描述**
有一个数据集，需要跟同伴共享数据集，请问如何建立这样的文件夹？

**问题针对于集群系统还是普适于Linux系统？**
针对集群系统

**集群文档是否有相关内容？**
文档架构里有说到有课题组共享文件夹和集体共享文件夹，但是没讲如何创建，也没讲特定人群共享文件夹。

Thanks in advance~

**Comment by ShenhanQian** [comment]
目前，共享文件夹需要管理员进行手动操作，仅支持创建课题组内部共享文件夹，不能由用户任意指定。

**Comment by JustLuoxi** [comment]
> 目前，共享文件夹需要管理员进行手动操作，仅支持创建课题组内部共享文件夹，不能由用户任意指定。

好的 多谢解答 我去申请下
