### ISSUE TITLE
How to use visdom in computing node in G-cluster

### ISSUE THREAD

**Issue by YohnGuan** [hpc-admin-sist/DockerMonitorG#2]
**问题描述**
问题背景
在G-cluster上，我想要在计算节点开启visdom并在自己的PC上访问，visdom的端口号为管理员所分配的。因为我自己的PC（在上科大内网）无法直接访问计算节点，所以按照10.15.89.41中的端口转发指令`ssh -CNfR 21370:localhost:21370 admin`进行操作，可是显示`ssh: Could not resolve hostname admin: Temporary failure in name resolution`。 我怀疑这是因为G-cluster的管理节点名称与AI-cluster不一致。

请问我需要怎么操作才能在自己PC访问visdom？

**问题针对于集群系统还是普适于Linux系统？**
是否有已知的问题解答？
普适于Linux系统

**集群文档是否有相关内容？**
集群文档是否涉及，是否存在错误，是否需要更新或补充？

**Comment by ShenhanQian** [comment]
G-Cluster的登录节点名称为`login`，请使用`ssh -CNfR 21370:localhost:21370 login`进行端口转发。
